-- Realistic Seed Scholarships for ScholarNest Development and Demo
-- Covers diverse criteria: Merit, Income, Gender, State, STEM, Category, etc.

INSERT INTO scholarships (
    id, name, provider, description, amount, course_eligibility, minimum_cgpa, 
    maximum_income, eligible_states, eligible_categories, gender_requirement, 
    age_requirement, required_documents, deadline, official_url, application_method, verified, status
) VALUES 
(
    '00000000-0000-0000-0000-000000000001',
    'Central Sector Scheme of Scholarships for College and University Students',
    'Ministry of Education, Government of India',
    'Provides financial assistance to meritorious students from low-income families to meet day-to-day expenses while pursuing higher studies in colleges and universities.',
    20000.00,
    '["All", "B.Tech", "B.Sc", "B.Com", "B.A", "MBBS"]'::jsonb,
    7.5,
    450000.00,
    '["All India"]'::jsonb,
    '["All", "General", "OBC", "SC", "ST", "EWS"]'::jsonb,
    'All',
    25,
    '["Income Certificate", "Academic Marksheet", "Aadhaar Card", "Bonafide Certificate", "Bank Passbook"]'::jsonb,
    '2026-11-30',
    'https://scholarships.gov.in',
    'National Scholarship Portal (NSP)',
    TRUE,
    'ACTIVE'
),
(
    '00000000-0000-0000-0000-000000000002',
    'Reliance Foundation Undergraduate Scholarship',
    'Reliance Foundation',
    'Supports meritorious undergraduate students across all disciplines with comprehensive grant and mentorship support through their degree programs.',
    200000.00,
    '["B.Tech", "B.Sc", "B.Com", "B.A", "BBA", "B.Des"]'::jsonb,
    8.0,
    1500000.00,
    '["All India"]'::jsonb,
    '["All"]'::jsonb,
    'All',
    22,
    '["Class 12 Marksheet", "College ID / Bonafide", "Family Income Certificate", "Aadhaar Card"]'::jsonb,
    '2026-10-25',
    'https://www.scholarships.reliancefoundation.org',
    'Reliance Foundation Portal',
    TRUE,
    'ACTIVE'
),
(
    '00000000-0000-0000-0000-000000000003',
    'Adobe India Women-in-Technology Scholarship',
    'Adobe Systems India',
    'Recognizes outstanding female students pursuing degrees in Computer Science, AI, and related Engineering disciplines, aiming to close the gender gap in tech leadership.',
    100000.00,
    '["B.Tech", "M.Tech", "B.E", "Dual Degree CSE/IT/ECE"]'::jsonb,
    8.5,
    2500000.00,
    '["All India"]'::jsonb,
    '["All"]'::jsonb,
    'Female',
    26,
    '["Resume", "College Marksheet", "Bonafide Certificate", "Technical Essay / Statement of Purpose", "Recommendation Letter"]'::jsonb,
    '2026-11-15',
    'https://www.adobe.com/in/careers/university/women-in-technology.html',
    'Adobe Careers Portal',
    TRUE,
    'ACTIVE'
),
(
    '00000000-0000-0000-0000-000000000004',
    'AICTE Pragati Scholarship Scheme for Girl Students',
    'All India Council for Technical Education (AICTE)',
    'Empowers young women to pursue technical diploma and degree education by providing annual tuition and sustenance grants.',
    50000.00,
    '["B.Tech", "B.Arch", "B.Pharmacy", "Diploma Engineering"]'::jsonb,
    7.0,
    800000.00,
    '["All India"]'::jsonb,
    '["All", "General", "OBC", "SC", "ST"]'::jsonb,
    'Female',
    24,
    '["AICTE College Admission Proof", "Income Certificate", "Caste Certificate", "Academic Marksheet", "Aadhaar Card"]'::jsonb,
    '2026-12-10',
    'https://www.aicte-india.org/schemes/students-development-schemes/pragati',
    'National Scholarship Portal',
    TRUE,
    'ACTIVE'
),
(
    '00000000-0000-0000-0000-000000000005',
    'ONGC Merit Scholarship for SC/ST and OBC Students',
    'ONGC Foundation',
    'Provides substantial financial support to disadvantaged students enrolled in Engineering, Medical (MBBS), and Masters in Geophysics/Geology or MBA programs.',
    48000.00,
    '["B.Tech", "MBBS", "MBA", "M.Sc Geophysics"]'::jsonb,
    6.5,
    200000.00,
    '["All India"]'::jsonb,
    '["SC", "ST", "OBC"]'::jsonb,
    'All',
    30,
    '["Caste Certificate", "Income Certificate", "College Bonafide", "Class 12 / Semester Marksheet", "Bank Passbook"]'::jsonb,
    '2026-11-05',
    'https://www.ongcscholar.org',
    'ONGC Foundation Portal',
    TRUE,
    'ACTIVE'
),
(
    '00000000-0000-0000-0000-000000000006',
    'Telangana ePASS Post-Matric Overseas & State Scholarship',
    'Government of Telangana Welfare Department',
    'Comprehensive fee reimbursement and maintenance allowance for SC, ST, BC, and EBC students studying in colleges across Telangana.',
    35000.00,
    '["B.Tech", "Degree", "B.Pharmacy", "MBA", "MCA", "Medical"]'::jsonb,
    6.0,
    200000.00,
    '["Telangana"]'::jsonb,
    '["SC", "ST", "OBC", "EWS"]'::jsonb,
    'All',
    28,
    '["Telangana Residence/Nativity Certificate", "Income Certificate issued by MeeSeva", "Caste Certificate", "Aadhaar Card", "Bonafide Certificate"]'::jsonb,
    '2026-10-31',
    'https://telanganaepass.cgg.gov.in',
    'Telangana ePASS Portal',
    TRUE,
    'ACTIVE'
),
(
    '00000000-0000-0000-0000-000000000007',
    'Tata Trust Medical and Healthcare Professional Grant',
    'Tata Trusts Education Grants',
    'Supports undergraduate and postgraduate students enrolled in recognized medical, nursing, and dental institutions in India.',
    75000.00,
    '["MBBS", "BDS", "B.Sc Nursing", "BAMS", "BHMS"]'::jsonb,
    7.5,
    500000.00,
    '["All India"]'::jsonb,
    '["All"]'::jsonb,
    'All',
    27,
    '["College Fee Receipt", "Annual Family Income Proof", "Yearly Marksheet", "Identity Card", "Statement of Need"]'::jsonb,
    '2026-12-15',
    'https://www.tatatrusts.org/our-work/individual-grants-programme/education-grants',
    'Tata Trusts Grants Portal',
    TRUE,
    'ACTIVE'
),
(
    '00000000-0000-0000-0000-000000000008',
    'Kotak Kanya Scholarship for Girl Students',
    'Kotak Education Foundation',
    'Assists talented girls from low-income families in completing professional graduation courses including engineering, architecture, design, and medicine.',
    150000.00,
    '["B.Tech", "MBBS", "B.Des", "B.Arch", "B.Pharma", "Integrated LLB"]'::jsonb,
    8.0,
    320000.00,
    '["All India"]'::jsonb,
    '["All"]'::jsonb,
    'Female',
    23,
    '["Class 12 Marksheet (>= 85%)", "Income Certificate (< 3.2 LPA)", "College Admission Letter", "Aadhaar Card", "Parent ID Proof"]'::jsonb,
    '2026-11-20',
    'https://kotakeducation.org/kotak-kanya-scholarship/',
    'Kotak Education Portal',
    TRUE,
    'ACTIVE'
),
(
    '00000000-0000-0000-0000-000000000009',
    'Sitaram Jindal Foundation Educational Scholarship',
    'Sitaram Jindal Foundation',
    'Financial scholarship for needy meritorious students pursuing Diploma, Degree, Technical, and Postgraduate programs.',
    24000.00,
    '["All", "B.Tech", "B.Sc", "B.Com", "Diploma"]'::jsonb,
    6.5,
    400000.00,
    '["All India"]'::jsonb,
    '["All"]'::jsonb,
    'All',
    25,
    '["Previous Exam Marksheet", "Income Certificate", "Bonafide Certificate", "BPL/Ration Card if applicable"]'::jsonb,
    '2026-12-31',
    'https://www.sitaramjindalfoundation.org/scholarships.php',
    'Foundation Direct Application',
    TRUE,
    'ACTIVE'
),
(
    '00000000-0000-0000-0000-000000000010',
    'Post-Matric Scholarship Scheme for Minorities',
    'Ministry of Minority Affairs, Govt of India',
    'Scholarship scheme encouraging students belonging to minority communities (Muslim, Christian, Sikh, Buddhist, Jain, Parsi) to continue higher education.',
    12000.00,
    '["All", "B.Tech", "Degree", "Medical", "Arts", "Commerce"]'::jsonb,
    5.5,
    250000.00,
    '["All India"]'::jsonb,
    '["Minority"]'::jsonb,
    'All',
    30,
    '["Minority Community Declaration", "Income Certificate", "Marksheet", "Bank Passbook", "Aadhaar Card"]'::jsonb,
    '2026-10-20',
    'https://scholarships.gov.in',
    'National Scholarship Portal',
    TRUE,
    'ACTIVE'
);
